problem:
  type: ReactiveEuler
  parameters:
    gamma: 1.2
    activation energy: 28.66
    heat release: 50.0
  frame: Shock
  initial: ZND
  boundary: Zero gradient
domain:
  left boundary: -30.0
  right boundary: 0.0
  nodes: 601
  timespan: 400.0
methods:
  space: WENO5M
  time: TVDRK3
upstream:
  type: Uniform
  parameters:
    density amplitude: 0.0
    density wavenumber: 0.0
    lambda amplitude: 0.0
    lambda wavenumber: 0.0
callbacks:
  write seconds: yes
  write video: no
  plot final solution: yes
  write final solution: yes
  plot speed: yes
  write speed: yes
